### ISSUE TITLE
Custom condition 'RealBiome' can not be recognized by MythicMobs on 1.18.2.

### ISSUE THREAD

**Issue by Hakuyako** [StrangeOne101/RealBiomeCondition#4]
I'm sure my RealBiomeCondition plugin is 1.0.3 which should support 1.18.2.
I tested lots of time, changing minecraft server types, changing system of server, the problem still exist. 

I ask for help on discord channel and they tell me report a issue on github but there is no issue report part on that page, so I can only report the issue here.
If it bothers you I apologize for it.
If you can forward my issue there I appreciate it.

Log: https://pastebin.com/3BtLS1Zr

Server Details
- Minecraft Version: 1.18.2
- Server Flavour: Paper version git-Paper-290 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: af94364)
- Java Version: 17
- Bukkit Version: 1.18.2-R0.1-SNAPSHOT
- Iris Version: Iris v2.0.6-1.18.2
- Custom Biomes: 77

**Comment by StrangeOne101** [comment]
I understand why you are reporting it here, since you can't do it in the fork repository, but I'm marking this issue as invalid as the release you're using isn't a release made by this repository.

I will leave this open for a week and then close it. Hopefully by then, Volmit will have enabled issues and it can be put on there.
